name: 'bvm'
description: 'Downloads, installs, and sets up bvm for your project.'
author: 'David Sherret'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        . $GITHUB_ACTION_PATH/action.sh
