name: 'test'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - shell: bash -l {0}
        run: |
          bvm -v
          bvm registry add https://bvm.land/deno/registry.json
          bvm install deno
      - run: deno -V
