name: 'test'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    name: test ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: macOS-latest
          - os: windows-2019
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          mkdir test-project
          echo "{ \"binaries\": [\"https://bvm.land/dprint/0.9.1.json\"] }" > test-project/bvm.json
      - uses: ./
      - run: dprint -v
      - if: matrix.config.os != 'windows-2019'
        run: |
          . $BVM_INSTALL_DIR/bin/bvm-init
          bvm -v
          bvm registry add https://bvm.land/deno/registry.json
          bvm install deno
      - if: matrix.config.os == 'windows-2019'
        run: |
          bvm -v
          bvm registry add https://bvm.land/deno/registry.json
          bvm install deno
      - run: deno -V
